<script src='https://www.google.com/recaptcha/api.js'></script>
<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$scopeConfig   = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface');

?>

<div class="row">
	
	<div class="col-sm-12">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('become_supplier')->toHtml();?>
	</div>

	<form class="form supplier"
		  action="<?php echo $this->getBaseUrl().'supplier/index/post';?>"
		  id="supplier-form"
		  method="post"
		  data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
		  data-mage-init='{"validation":{}}'>

		<div class="form-list">
			<div class="fields">
			<div class="field"> 
				<label class="label" for="Contact Person"><span><?php /* @escapeNotVerified */ echo __('Contact Person') ?></span></label>
				<div class="control">
					<input placeholder="Contact Person*" maxlength="100" name="contact_person" id="contact_person" title="<?php /* @escapeNotVerified */ echo __('Contact Person') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
				</div> 
			</div>
			
			<div class="field"> 
				<label class="label" for="Company Name*"><span><?php /* @escapeNotVerified */ echo __('Company Name') ?></span></label>
				<div class="control">
					<input placeholder="Company Name*" maxlength="100" name="company_name" id="company_name" title="<?php /* @escapeNotVerified */ echo __('Company Name') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
				</div> 
			</div> 
			</div>
            <div class="fields">
			<div class="field"> 
				<label class="label" for="Address"><span><?php /* @escapeNotVerified */ echo __('Address') ?></span></label>
				<div class="control">
					<input placeholder="Address*" maxlength="250" name="address" id="address" title="<?php /* @escapeNotVerified */ echo __('Address') ?>" value="" class="input-text" type="text"/>
				</div> 
			</div> 
			
			<div class="field">
				<label class="label" for="Website"><span><?php /* @escapeNotVerified */ echo __('Website') ?></span></label>
				<div class="control">
					<input placeholder="Website" maxlength="100" name="website" id="website" title="<?php /* @escapeNotVerified */ echo __('Website') ?>" class="input-text" type="text"/>
				</div>
			</div>
            </div>
			<div class="fields">
			<div class="field">
				<label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
				<div class="control">
					<input placeholder="Email*" maxlength="100" name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
				</div>
			</div>  
			<div class="field"> 
				<label class="label" for="phone_no"><span><?php /* @escapeNotVerified */ echo __('Phone No') ?></span></label>
				<div class="control">
					<input placeholder="Phone No" maxlength="50" name="phone_no" id="phone_no" title="<?php /* @escapeNotVerified */ echo __('Phone No') ?>" value="" class="input-text" type="text"/>
				</div> 
			</div> 
			</div>
            <div class="wide">
			<div class="field">
				<label class="label" for="message"><span><?php /* @escapeNotVerified */ echo __('Message') ?></span></label>
				<div class="control">
					<textarea placeholder="Message*" maxlength="1000" name="message" id="message" title="<?php /* @escapeNotVerified */ echo __('Message') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
				</div>
			</div>
			</div>
            <div class="fields">
            	<div class="field">
		<div class="gcaptcha_wrap">
		
			<div class="g-recaptcha" data-sitekey="6LcHtBwUAAAAAPpJ-Pc4uNGzBu9KJolHb1_IjXye"></div>
			<div class="recaptcha-error-message validation-advice" style="display:none;" ><?php /* @escapeNotVerified */ echo __('Please verify that you are not a robot.') ?></div>
		</div>
			<p class="required"><?php /* @escapeNotVerified */ echo __('(*) Required Field') ?></p>
			</div>
            <div class="field">
		<div class="actions-toolbar">
			<div class="primary">
				<input type="hidden" name="hideit" id="hideit" value="" />
				<button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
					<span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
				</button>
			</div>
		</div>
        </div>
	</div>			
	</form>
	
</div>
<script type="text/javascript">
 require([
        'jquery',
    ], function ($) {
		$(document).ready(function () {
 jQuery("#supplier-form").submit(function( event ) {
  var response = grecaptcha.getResponse();
                    if(response.length==0  )
                    {
                        jQuery('.recaptcha-error-message').css({'color':'#e02b27'}).show();
                        return false; // Will stop the submission of the form
                    }
	 				else
					{
						 jQuery('.recaptcha-error-message').css({'color':'#e02b27'}).hide();
					}
 
});
var onSuccess = function(response) {
                       var errorDivs = document.getElementsByClassName("recaptcha-error");
                       if (errorDivs.length) {
                         errorDivs[0].className = "";
                       }
                       var errorMsgs = document.getElementsByClassName("recaptcha-error-message");
                       if (errorMsgs.length) {
                         errorMsgs[0].parentNode.removeChild(errorMsgs[0]);
                       }
                     };
});
});
</script>