<div class="block newsletter">
    <div class="title"><strong>Sign up for our Newsletter</strong></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label" for="newsletter"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Our Newsletter:') ?></span></label>
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Enter Your Email') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" type="submit">
                    <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
<div class="block socialmedia">
	<ul>
		<li class="facebook-link">
			<a title="Facebook" href="https://www.facebook.com/realsmart.com.au" target="_blank">Facebook</a>
		</li>
		<li class="pinterest-link">
			<a title="Pinterest" href="https://www.pinterest.com/realsmartaus/" target="_blank">Pinterest</a>
		</li>
	</ul>
</div>