<?php /* <link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Magento_Theme::css/owl.carousel.min.css')?>"> */ ?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('New Products');
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
}
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$baseUrl = $currentStore->getBaseUrl();
?>

<?php if ($exist):?>
    <div class="block widget block-new-products <?php /* @escapeNotVerified */ echo $mode; ?>">
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <div class="new-product-carousel product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                        	<div class="product-item-image-wrapper">
							
							<div class="product-label-wrapper">	
							<!-- New, Sale Icon -->
							<?php
								// Special Product								
								$specialprice = $_item->getSpecialPrice();							
								$specialPriceFromDate = $_item->getSpecialFromDate();							
								$specialPriceToDate = $_item->getSpecialToDate();
								$today = time();							
								$price = $_item->getPrice();
								$sale_status = 0;

								if($price){
									$sale = round((($price-$specialprice)/$price)*100);
								}
								if ($specialprice) {
									if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) {										
										echo '<div class="label sale-label">Sale</div>';
										$sale_status = 1;
									}
								}
					
								if ($sale_status == 0) {
								// New Product								
									$now = date("Y-m-d");
									$newsFrom = $_item->getNewFromDate();								
									$newsTo =  $_item->getNewsToDate();					

									if(($now >= $newsFrom) && ($now <= $newsTo)){
										echo '<div class="label new-label">New</div>';
									}
								}
					
							$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
							$product = $objectManager->create('Magento\Catalog\Model\Product')->load($_item->getId());				
							if($product->getProductFreeShippingIcon())
							{
								echo '<div class="label free-label">Free</div>';
							}

							?>						
							<!-- New, Sale Icon -->	
							</div>	
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <?php if ($showWishlist || $showCompare || $showCart){ ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>												
                                                      <?php
                                                      $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                      $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()]);
													  // checkout/cart/add/uenc/,,/product/6/
													?>
												
												<form data-role="tocart-form" action="<?php echo $baseUrl.'checkout/cart/add/product/'.$_item->getId(); ?>" method="post">												
													<input type="hidden" name="product" value="<?php echo $_item->getId(); ?>">
													<input type="hidden" name="uenc" value="">
													<?php echo $block->getBlockHtml('formkey') ?>
													<button type="submit"
															title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
															class="action tocart primary">
														<span><?php echo __('Add to Cart') ?></span>
													</button>
												</form>
												
												
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                       class="action towishlist" data-action="add-to-wishlist"
                                                       title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php } ?>
                              </div>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php
                                echo $block->getProductPriceHtml($_item, $type);
                                ?>

                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </div>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
	
<script type="text/x-magento-init">
	{
	"[data-role=tocart-form], .form.map.checkout": {
	"catalogAddToCart": {}
	}
	}
</script>
        
<script>
        require(['jquery','owlcarouselslider'], function () {
            jQuery(document).ready(function () {
				if(jQuery(window).width()>767)
				{
                jQuery(".new-product-carousel").owlCarousel({
     				nav : true,
					dots :false,
					responsive : {
						// breakpoint from 0 up
						0 : {
							items : 1,
						},
						639 : {
							items : 2,
						},
						768 : {
							items : 3,
						},
						// breakpoint from 480 up
						860 : {
							items : 4,
						},
						1080 : {
							items : 5,
						}
					}
                });
				}
            });
        });
</script>
