<?php if ($block->isEnabledModule()){ ?>
<script src='https://www.google.com/recaptcha/api.js'></script>
<div class="row">
	<div class="col-sm-12">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contactus')->toHtml();?>
	</div>
	<form class="form contact"
		  action="<?php echo $this->getBaseUrl().'contacts/index/post';?>"
		  id="contactus-form"
		  method="post"
		  data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
		  data-mage-init='{"validation":{}}'>

		<div class="form-list">
			<div class="fields">
			<div class="field"> 
				<label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('Name') ?></span></label>
				<div class="control">
					<input placeholder="Name*" maxlength="100" name="name" id="name" title="<?php /* @escapeNotVerified */ echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
				</div> 
			</div> 

			<div class="field">
				<label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
				<div class="control">
					<input placeholder="Email*" maxlength="100" name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
				</div>
			</div>  
			</div>
            <div class="fields">
			<div class="field">
				<label class="label" for="subject"><span><?php /* @escapeNotVerified */ echo __('Subject') ?></span></label>
				<div class="control">
					<input placeholder="Subject" maxlength="100" name="subject" id="subject" title="<?php /* @escapeNotVerified */ echo __('Subject') ?>" class="input-text" type="text"/>
				</div>
			</div>

			<div class="field"> 
				<label class="label" for="ordernumber"><span><?php /* @escapeNotVerified */ echo __('Order Number (if available)') ?></span></label>
				<div class="control">
					<input placeholder="Order Number" maxlength="50" name="ordernumber" id="ordernumber" title="<?php /* @escapeNotVerified */ echo __('Order Number') ?>" value="" class="input-text" type="text"/>
				</div> 
			</div> 
			</div>
            <div class="wide">
			<div class="field">
				<label class="label" for="message"><span><?php /* @escapeNotVerified */ echo __('Message') ?></span></label>
				<div class="control">
					<textarea placeholder="Message*" maxlength="1000" name="message" id="message" title="<?php /* @escapeNotVerified */ echo __('Message') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
				</div>
			</div>
			</div>
            <div class="fields">
            	<div class="field">
                	<div class="gcaptcha_wrap">
		
			<div class="g-recaptcha" data-sitekey="6LcHtBwUAAAAAPpJ-Pc4uNGzBu9KJolHb1_IjXye"></div>
			<div class="recaptcha-error-message validation-advice" style="display:none;" ><?php /* @escapeNotVerified */ echo __('Please verify that you are not a robot.') ?></div>
		</div>
					<p class="required"><?php /* @escapeNotVerified */ echo __('(*) Required Field') ?></p>
                </div>
				
				
				
                <div class="field">
                	<div class="actions-toolbar">
			<div class="primary">
				<input type="hidden" name="hideit" id="hideit" value="" />
				<button type="submit" title="<?php /* @escapeNotVerified */ echo __('Send Message') ?>" class="action submit primary">
					<span><?php /* @escapeNotVerified */ echo __('Send Message') ?></span>
				</button>
			</div>
		</div>
                </div>
            </div>
		</div>
	</form>
	
</div>
<script type="text/javascript">
 require([
        'jquery',
    ], function ($) {
		$(document).ready(function () {
 jQuery("#contactus-form").submit(function( event ) {
  var response = grecaptcha.getResponse();
                    if(response.length==0  )
                    {
                        jQuery('.recaptcha-error-message').css({'color':'#e02b27'}).show();
                        return false; // Will stop the submission of the form
                    }
	 				else
					{
						 jQuery('.recaptcha-error-message').css({'color':'#e02b27'}).hide();
					}
 
});
var onSuccess = function(response) {
                       var errorDivs = document.getElementsByClassName("recaptcha-error");
                       if (errorDivs.length) {
                         errorDivs[0].className = "";
                       }
                       var errorMsgs = document.getElementsByClassName("recaptcha-error-message");
                       if (errorMsgs.length) {
                         errorMsgs[0].parentNode.removeChild(errorMsgs[0]);
                       }
                     };
});
});
</script>
<?php } else {
echo 'Please enable module first!!';
} ?>