<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php //echo $this->getHelloWorldTxt(); ?>
<?php
//$enableModule = $block->getSectionStatus();
if($this->getSlideAuto() == 1) $slide_auto = 'true'; else $slide_auto = 'false';
if($this->getPagination() == 1) $slide_pagination = 'true'; else $slide_pagination = 'false';
if($this->getNavigation() == 1) $slide_navigation = 'true'; else $slide_navigation = 'false';
//if ($enableModule) {
    $block_title = $block->getPageTitle();
    $_productCollection = $block->getLoadedProductCollection();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $imageBlock = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
    ?>
    <?php if (!$_productCollection->count()): ?>
        <div class="message info empty"><div><?php echo __('1We can\'t find products matching the selection.') ?></div></div>
    <?php else: ?>
        <?php

            $viewMode = 'grid';
            //$image = 'category_page_grid';
			$image = 'new_products_content_widget_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
       
        /*if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $image = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode = 'list';
            $image = 'category_page_list';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }*/
        $pos = $block->getPositioned();
        $position = '';
        if ($pos != null) {
            $position = ' style="left:' . $block->getVar("{$image}:width") . 'px;'
                    . 'top:' . $block->getVar("{$image}:height") . 'px;"';
        }
        ?>
		<div class="block widget block-bestseller-products <?php echo $viewMode; ?>">
			<div class="block-content">				
				<div class="products-<?php echo $viewMode; ?> <?php echo $viewMode; ?>">			
			<?php $iterator = 1; ?>
			<div class="best-seller-carousel product-items bestsellerproducts">
				<?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
				<?php foreach ($_productCollection as $_product): ?>
					<?php echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
					<div class="product-item-info" data-container="product-grid">						
					
						
						<?php // Product Image    ?>
						<div class="product-item-image-wrapper">
							<div class="product-label-wrapper">	
							<!-- New, Sale Icon -->
							<?php
								// Special Product
								$specialprice = $_product->getSpecialPrice();							
								$specialPriceFromDate = $_product->getSpecialFromDate();							
								$specialPriceToDate = $_product->getSpecialToDate();
								$today = time();							
								$price = $_product->getPrice();
								$sale_status = 0;

								if($price){
									$sale = round((($price-$specialprice)/$price)*100);
								}
								if ($specialprice) {
									if ($today >= strtotime($specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime($specialPriceFromDate) && is_null($specialPriceToDate)) {
										//if($sale) { echo $sale.'%'; } else {echo __('Sale');}
										echo '<div class="label sale-label">Sale</div>';
										$sale_status = 1;
									}
								}
							
								if ($sale_status == 0) {
								// New Product								
									$now = date("Y-m-d");
									$newsFrom = $_product->getNewFromDate();								
									$newsTo =  $_product->getNewsToDate();					

									if(($now >= $newsFrom) && ($now <= $newsTo)){
										echo '<div class="label new-label">New</div>';
									}
								}	

							?>						
							<!-- New, Sale Icon -->
							</div>
							<a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
								<span class="product-image-container">
									<span class="product-image-wrapper">
									<?php /* ?>
										<?php
										$imageUrl = $this->helper('Magento\Catalog\Helper\Image')
												->init($_product, 'product_page_image_large')
												->constrainOnly(FALSE)
												->keepAspectRatio(TRUE)
												->keepFrame(FALSE)
												->resize(226, 257)
												->getUrl();
										?>										
									<img class="product-image-photo" src="<?php echo $imageUrl; ?>" width="226" height="257" />
									<?php */ ?>
										<!--<img class="product-image-photo" src="<?php //echo $this->helper('Magento\Catalog\Helper\Image')->init($_product, 'image');?>"height="240" width="240" />-->
										
										<?php
										$imageUrl = $this->helper('Magento\Catalog\Helper\Image')
												->init($_product, 'product_page_image_large')
												->constrainOnly(FALSE)
												->keepAspectRatio(TRUE)
												->keepFrame(TRUE)
												->resize(226, 257)
												->getUrl();
										?>										
										<img class="product-image-photo" src="<?php echo $imageUrl; ?>" />
									</span>
								</span>
							</a>
							
							<!-- Add to cart & Whishlist Button -->
								<div class="product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
									<div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
										<?php if ($_product->isSaleable()): ?>
											<?php $postParams = $block->getAddToCartPostParams($_product); ?>
											<form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post">
												<input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
												<input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
												<?php echo $block->getBlockHtml('formkey') ?>
												<button type="submit"
														title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
														class="action tocart primary">
													<span><?php echo __('Add to Cart') ?></span>
												</button>
											</form>
										<?php else: ?>
											<?php if ($_product->getIsSalable()): ?>
												<div class="stock available"><span><?php echo __('In stock') ?></span></div>
											<?php else: ?>
												<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
											<?php endif; ?>
										<?php endif; ?>
									</div>
									<div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
											<a href="#"
											   class="action towishlist"
											   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
											   data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
											   data-action="add-to-wishlist"
											   role="button">
												<span><?php echo __('Add to Wish List') ?></span>
											</a>
										<?php endif; ?>
										<?php /* ?>
										<?php
										$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
										?>
										<a href="#"
										   class="action tocompare"
										   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
										   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
										   data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
										   role="button">
											<span><?php echo __('Add to Compare') ?></span>
										</a>
										<?php */ ?>
									</div>
								</div>
							<!-- Add to cart & Whishlist Button -->
						</div>

						<div class="product details product-item-details">
							<div style="padding: 0 2px;"><?php echo $block->getProductDetailsHtml($_product); ?></div>
							<?php
							$_productNameStripped = $block->stripTags($_product->getName(), null, true);
							?>
							<strong class="product name product-item-name">
								<a class="product-item-link"
								   href="<?php echo $_product->getProductUrl() ?>">
									   <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
								</a>
							</strong>
							<?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
							<?php echo $block->getProductPrice($_product) ?>

							
								<?php /* ?>
								<?php if ($showDescription): ?>
									<div class="product description product-item-description">
										<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
										<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>"
										   class="action more"><?php echo __('Learn More') ?></a>
									</div>
								<?php endif; ?>
							<?php */ ?>
							
							
							
							
						</div>
					</div>
					<?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
				<?php endforeach; ?>
			</div>
			<?php /* ?><div class="view-all"><a href="<?php echo $this->getUrl('bestsellerproducts') ?>"><?php echo __('View all') ?></a></div><?php */ ?>
			
			
				</div>			
			</div>	
			
        </div>

		<?php if (!$block->isRedirectToCartEnabled()) : ?>
            <script type="text/x-magento-init">
                {
                "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
                }
                }
            </script>
        <?php endif; ?>
    <?php endif; ?>


<script>
        require(['jquery','owlcarouselslider'], function () {
            jQuery(document).ready(function () {
				if(jQuery(window).width()>767)
				{
                jQuery(".best-seller-carousel").owlCarousel({
                   nav : true,
					dots :false,
					responsive : {
					// breakpoint from 0 up
					0 : {
						items : 1,
					},
					639 : {
						items : 2,
					},
					768 : {
						items : 3,
					},
					// breakpoint from 480 up
					860 : {
						items : 4,
					},
					1080 : {
						items : 5,
					}
				}
                });
				}
            });
        });
</script>
